lan_complain/urls.py
from django.conf.urls import url

from lan_complain import views

urlpatterns = [
    url(r'^$', views.questions, name='questions'),
    url(r'^answered/$', views.answered, name='answered'),
    url(r'^unanswered/$', views.unanswered, name='unanswered'),
    url(r'^all/$', views.all, name='all'),
    url(r'^ask/$', views.ask, name='ask'),
    url(r'^favorite/$', views.favorite, name='favorite'),
    url(r'^answer/$', views.answer, name='answer'),
    url(r'^answer/accept/$', views.accept, name='accept'),
    url(r'^answer/vote/$', views.vote, name='vote'),
    url(r'^(?P<pk>[\-\w]+)/$', views.question, name='question'),
]

por/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from search import views as search_views
from django.conf import settings
from django.conf.urls.static import static
from activities import views as activities_views
urlpatterns = [
    url(r'^$',views.site_redirect),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/',views.home),
    url(r'^accounts/profile_edit/(?P<pk>[\-\w]+)/$', views.edit_user, name='account_update'),
    url(r'^accounts/profile_view/(?P<pk>[\-\w]+)/$',views.get_user, name = 'account_view'),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^profile/(?P<username>[^/]+)/$', views.profile, name='profile'),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    url(r'', include('events.urls')),
    url(r'^messages/', include('messenger.urls')),
    url(r'^settings/picture/$', views.picture, name='picture'),
    url(r'^settings/upload_picture/$', views.upload_picture,
        name='upload_picture'),
    url(r'^settings/save_uploaded_picture/$', views.save_uploaded_picture,
        name='save_uploaded_picture'),
    url(r'^feeds/', include('feeds.urls')),
    url(r'^lan_complain/', include('lan_complain.urls')),
    url(r'^enotices/', include('enotices.urls')),
    url(r'^notifications/$', activities_views.notifications,
        name='notifications'),
    url(r'^notifications/last/$', activities_views.last_notifications,
        name='last_notifications'),
    url(r'^notifications/check/$', activities_views.check_notifications,
        name='check_notifications'),
    url(r'^LostAndFound/', include('lost_found.urls', namespace="laf")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

lan_complain/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

import markdown
from activities.models import Activity


@python_2_unicode_compatible
class Question(models.Model):
    HOSTEL_CHOICES = (
        ('0', 'S.N.Bose '),
        ('1', 'Aryabhatta '),
        ('2', 'S. Ramanujan '),
        ('3', 'C. V. Raman'),
        ('4', 'Morvi'),
        ('5', 'Dhanrajgiri'),
        ('6', 'Rajputana'),
        ('7', 'Limbdi'),
        ('8', 'S.C. De'),
        ('9', 'Vishweshvarayya'),
        ('10', 'Vivekanand'),
        ('11', 'Vishwakarma'),
        ('12', 'Gandhi Smriti Mahila Chhatravas'),
        ('13', 'New Girls GSMC Extn.'),
        ('14', 'Saluja'),

    )

    user = models.ForeignKey(User)

    description = models.TextField(max_length=2000)
    hostel = models.CharField(max_length=100, choices=HOSTEL_CHOICES, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now_add=True)
    favorites = models.IntegerField(default=0)
    has_accepted_answer = models.BooleanField(default=False)


    class Meta:
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'
        ordering = ('-update_date',)

    def __str__(self):
        return self.title

    @staticmethod
    def get_unanswered():
        return Question.objects.filter(has_accepted_answer=False)

    @staticmethod
    def get_answered():
        return Question.objects.filter(has_accepted_answer=True)

    def get_answers(self):
        return Answer.objects.filter(question=self)

    def get_answers_count(self):
        return Answer.objects.filter(question=self).count()

    def get_accepted_answer(self):
        return Answer.objects.get(question=self, is_accepted=True)

    def get_description_as_markdown(self):
        return markdown.markdown(self.description, safe_mode='escape')

    def get_description_preview(self):
        if len(self.description) > 255:
            return '{0}...'.format(self.description[:255])
        else:
            return self.description

    def get_description_preview_as_markdown(self):
        return markdown.markdown(self.get_description_preview(),
                                 safe_mode='escape')

    def calculate_favorites(self):
        favorites = Activity.objects.filter(activity_type=Activity.FAVORITE,
                                            question=self.pk).count()
        self.favorites = favorites
        self.save()
        return self.favorites

    def get_favoriters(self):
        favorites = Activity.objects.filter(activity_type=Activity.FAVORITE,
                                            question=self.pk)
        favoriters = []
        for favorite in favorites:
            favoriters.append(favorite.user)
        return favoriters

    def create_tags(self, tags):
        tags = tags.strip()
        tag_list = tags.split(' ')
        for tag in tag_list:
            t, created = Tag.objects.get_or_create(tag=tag.lower(),
                                                   question=self)

    def get_tags(self):
        return Tag.objects.filter(question=self)


@python_2_unicode_compatible
class Answer(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    description = models.TextField(max_length=2000)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(null=True, blank=True)
    votes = models.IntegerField(default=0)
    is_accepted = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Answer'
        verbose_name_plural = 'Answers'
        ordering = ('-is_accepted', '-votes', 'create_date',)

    def __str__(self):
        return self.description

    def accept(self):
        answers = Answer.objects.filter(question=self.question)
        for answer in answers:
            answer.is_accepted = False
            answer.save()
        self.is_accepted = True
        self.save()
        self.question.has_accepted_answer = True
        self.question.save()

    def calculate_votes(self):
        up_votes = Activity.objects.filter(activity_type=Activity.UP_VOTE,
                                           answer=self.pk).count()
        down_votes = Activity.objects.filter(activity_type=Activity.DOWN_VOTE,
                                             answer=self.pk).count()
        self.votes = up_votes - down_votes
        self.save()
        return self.votes

    def get_up_voters(self):
        votes = Activity.objects.filter(activity_type=Activity.UP_VOTE,
                                        answer=self.pk)
        voters = []
        for vote in votes:
            voters.append(vote.user)
        return voters

    def get_down_voters(self):
        votes = Activity.objects.filter(activity_type=Activity.DOWN_VOTE,
                                        answer=self.pk)
        voters = []
        for vote in votes:
            voters.append(vote.user)
        return voters

    def get_description_as_markdown(self):
        return markdown.markdown(self.description, safe_mode='escape')


@python_2_unicode_compatible
class Tag(models.Model):
    tag = models.CharField(max_length=50)
    question = models.ForeignKey(Question)

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'
        unique_together = (('tag', 'question'),)
        index_together = [['tag', 'question'], ]

    def __str__(self):
        return self.tag

lan_complain/forms.py
from django import forms

from lan_complain.models import Answer, Question


class QuestionForm(forms.ModelForm):

    hostel = forms.ChoiceField(choices=Question.HOSTEL_CHOICES,widget=forms.Select(attrs={'class':'selector'}))

    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'}),
        max_length=2000)
    tags = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=255,
        required=False,
        help_text='Use spaces to separate the tags, such as "asp.net mvc5 javascript"')  # noqa: E501

    class Meta:
        model = Question
        fields = ['hostel', 'description', 'tags']


class AnswerForm(forms.ModelForm):
    question = forms.ModelChoiceField(widget=forms.HiddenInput(),
                                      queryset=Question.objects.all())
    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '4'}),
        max_length=2000)

    class Meta:
        model = Answer
        fields = ['question', 'description']

lan_complain/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render

from activities.models import Activity
from por.decorators import ajax_required
from lan_complain.forms import AnswerForm, QuestionForm
from lan_complain.models import Answer, Question


@login_required
def _questions(request, questions, active):
    paginator = Paginator(questions, 10)
    page = request.GET.get('page')
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)
    return render(request, 'lan_complain/questions.html', {
        'questions': questions,
        'active': active
    })


@login_required
def questions(request):
    return unanswered(request)


@login_required
def answered(request):
    questions = Question.get_answered()
    return _questions(request, questions, 'answered')


@login_required
def unanswered(request):
    questions = Question.get_unanswered()
    return _questions(request, questions, 'unanswered')


@login_required
def all(request):
    questions = Question.objects.all()
    return _questions(request, questions, 'all')


@login_required
def ask(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = Question()
            question.user = request.user
            question.hostel = form.cleaned_data.get('hostel')
            question.description = form.cleaned_data.get('description')
            question.save()
            tags = form.cleaned_data.get('tags')
            question.create_tags(tags)
            return redirect('/lan_complain/')

        else:
            return render(request, 'lan_complain/ask.html', {'form': form})

    else:
        form = QuestionForm()

    return render(request, 'lan_complain/ask.html', {'form': form})


@login_required
def question(request, pk):
    question = get_object_or_404(Question, id=pk)
    form = AnswerForm(initial={'question': question})
    return render(request, 'lan_complain/question.html', {
        'question': question,
        'form': form
    })


@login_required
def answer(request):
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            user = request.user
            answer = Answer()
            answer.user = request.user
            answer.question = form.cleaned_data.get('question')
            answer.description = form.cleaned_data.get('description')
            answer.save()
            user.profile.notify_answered(answer.question)
            return redirect('/lan_complain/{0}/'.format(answer.question.pk))
        else:
            question = form.cleaned_data.get('question')
            return render(request, 'lan_complain/question.html', {
                'question': question,
                'form': form
            })
    else:
        return redirect('/lan_complain/')


@login_required
@ajax_required
def accept(request):
    answer_id = request.POST['answer']
    answer = Answer.objects.get(pk=answer_id)
    user = request.user
    try:
        # answer.accept cleans previous accepted answer
        user.profile.unotify_accepted(answer.question.get_accepted_answer())

    except Exception:
        pass

    if answer.question.user == user:
        answer.accept()
        user.profile.notify_accepted(answer)
        return HttpResponse()

    else:
        return HttpResponseForbidden()


@login_required
@ajax_required
def vote(request):
    answer_id = request.POST['answer']
    answer = Answer.objects.get(pk=answer_id)
    vote = request.POST['vote']
    user = request.user
    activity = Activity.objects.filter(
        Q(activity_type=Activity.UP_VOTE) | Q(activity_type=Activity.DOWN_VOTE),   # noqa: E501
        user=user, answer=answer_id)
    if activity:
        activity.delete()
    if vote in [Activity.UP_VOTE, Activity.DOWN_VOTE]:
        activity = Activity(activity_type=vote, user=user, answer=answer_id)
        activity.save()
    return HttpResponse(answer.calculate_votes())


@login_required
@ajax_required
def favorite(request):
    question_id = request.POST['question']
    question = Question.objects.get(pk=question_id)
    user = request.user
    activity = Activity.objects.filter(activity_type=Activity.FAVORITE,
                                       user=user, question=question_id)
    if activity:
        activity.delete()
        user.profile.unotify_favorited(question)
    else:
        activity = Activity(activity_type=Activity.FAVORITE, user=user,
                            question=question_id)
        activity.save()
        user.profile.notify_favorited(question)

    return HttpResponse(question.calculate_favorites())

templates/lan_complain/ask.html
{% extends 'home.html' %}
{% load i18n %}

{% block apps %}
    <div class="profile-content">
  <ol class="breadcrumb">
    <li><a href="{% url 'questions' %}">{% trans 'Complains' %}</a></li>
    <li class="active">{% trans 'Register Your Complain'  %}</li>
  </ol>
  <form action="{% url 'ask' %}" method="post" class="form-horizontal" role="form">
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.label }}" class="col-sm-2 control-label">{{ field.label }}</label>
        <div class="col-sm-10">
          {% if field.label == 'Description' %}
            {% include 'markdown_editor.html' with textarea='id_description' %}
          {% endif %}
          {{ field }}
          {% if field.help_text %}
            <span class="help-block">{{ field.help_text }}</span>
          {% endif %}
          {% for error in field.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">{% trans 'Answer' %}</button>
        <a href="{% url 'questions' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
      </div>
    </div>
  </form>
    </div>
{% endblock apps %}

templates/lan_complain/partial_answer.html
{% load i18n %}
{% load humanize %}

<div class="row answer" answer-id="{{ answer.id }}">
  {% csrf_token %}
  <div class="col-md-1 options">
    <span class="glyphicon glyphicon-chevron-up vote up-vote{% if user in answer.get_up_voters %} voted{% endif %}" title="{% trans 'Click to up vote; click again to toggle' %}"></span>
    <span class="votes">{{ answer.votes }}</span>
    <span class="glyphicon glyphicon-chevron-down vote down-vote{% if user in answer.get_down_voters %} voted{% endif %}" title="{% trans 'Click to down vote; click again to toggle' %}"></span>
    {% if answer.is_accepted and user == question.user %}
      <span class="glyphicon glyphicon-ok accept accepted" title="{% trans 'Click to unaccept the answer' %}"></span>
    {% elif answer.is_accepted %}
      <span class="glyphicon glyphicon-ok accept accepted" style="cursor: default"></span>
    {% elif user == question.user %}
      <span class="fa fa-thumbs-up thumbs-down" title="{% trans 'Click to accept the answer' %}"></span>
    {% endif %}
  </div>
  <div class="col-md-11">
    <div class="answer-user">
      <a href="{% url 'profile' answer.user.username %}"><img src="{{ answer.user.userprofile.get_picture }}" class="user"></a>
      <a href="{% url 'profile' answer.user.username %}" class="username">{{ answer.user.first_name }} {{ answer.user.last_name }} ({{ answer.user.username }})</a>

    </div>
    <div class="answer-description">
      {{ answer.get_description_as_markdown|safe }}
    </div>
      <small class="answered">{% trans "answered" %} {{ answer.create_date|naturaltime }}</small>
  </div>
</div>
<hr>

templates/lan_complain/partial_question.html
{% load humanize %}

<div class="panel panel-default question" question-id="{{ question.id }}">
  <div class="panel-heading">
    <h3 class="panel-title">
      {% if question.has_accepted_answer %}
        <span class="fa fa-check"></span>
      {% endif %}
      <a href="{% url 'question' pk=question.id %}">{{ question.get_hostel_display }}</a>
    </h3>
  </div>
  <div class="panel-body clearfix">
    <div class="question-info">
      <div class="info">
        <h5><span class="fa fa-comment"></span> Answers</h5>
        <span>{{ question.get_answers_count }}</span>
      </div>
      <div class="info">
        <h5><span class="fa fa-star"></span> Favorites</h5>
        <span>{{ question.favorites }}</span>
      </div>
    </div>
    <div class="question-user">
      <a href="{% url 'profile' question.user.username %}"><img src="{{ question.user.userprofile.get_picture }}" class="user"></a>

        <a href="{% url 'profile' question.user.username %}" class="username">{{ question.user.first_name }} {{ question.user.last_name }} ({{ question.user.username }})</a>


    </div>
    <div class="question-description">
      {{ question.get_description_preview_as_markdown|safe }}
        <span class="asked">asked {{ question.update_date|naturaltime }}</span>
    </div>

    {% if question.get_tags %}
      <p>
        {% for tag in question.get_tags %}
          <span class="label label-primary">{{ tag }}</span>
        {% endfor %}
      </p>
    {% endif %}
  </div>
</div>

templates/lan_complain/question.html
{% extends 'home.html' %}
{% load staticfiles %}
{% load i18n %}
{% load humanize %}




{% block apps %}
    <div class="profile-content">
  <ol class="breadcrumb">
    <li><a href="{% url 'questions' %}">{% trans "Complains" %}</a></li>
    <li class="active">{% trans "Complain" %}</li>
  </ol>

        <div class="row question"  question-id="{{ question.id }}">
            {% csrf_token %}
                <div class="col-md-1 options">
                    {% if user in question.get_favoriters %}
                        <span class="glyphicon glyphicon-star favorite favorited" title="Click to mark this complain as favorite; click again to toggle"></span>
                    {% else %}
                        <span class="glyphicon glyphicon-star-empty favorite" title="Click to mark this complain as favorite; click again to toggle"></span>
                    {% endif %}
                    <span class="favorite-count">{{ question.favorites }}</span>
                </div>
                <div class="col-md-11">
                    <h2>{{ question.title }}</h2>
                    <div class="question-user">
                        <a href="{% url 'profile' question.user.username %}"><img src="{{ question.user.userprofile.get_picture }}" class="user"></a>
                        <a href="{% url 'profile' question.user.username %}" class="username">{{ question.user.first_name }} {{ question.user.last_name }} ({{ question.user.username }})</a>

                    </div>
                    <div class="question-description">
                        {{ question.get_description_as_markdown|safe }}

                    </div>

                    {% if question.get_tag_list %}
                        <p>
                            {% for tag in question.get_tag_list %}
                                <span class="label label-primary">{{ tag }}</span>
                            {% endfor %}
                        </p>
                    {% endif %}
                <small class="asked">asked {{ question.update_date|naturaltime }}</small>
                </div>

        </div>

  <h4 class="page-header">Answers</h4>
  <div class="answers">
    {% for answer in question.get_answers %}
      {% include 'lan_complain/partial_answer.html' with question=question answer=answer %}
    {% endfor %}
    <h4>Your Answer</h4>
    <form action="{% url 'answer' %}" method="post" role="form">
      {% csrf_token %}
      {{ form.question }}
      <div class="form-group">
        {% include 'markdown_editor.html' with textarea='id_description' %}
        {{ form.description }}
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary">{% trans "Post Your Answer"%}</button>
      </div>
    </form>
  </div>
    </div>
{% endblock apps %}

templates/lan_complain/questions.html
{% extends 'home.html' %}
{% load staticfiles %}
{% load i18n %}
{% load humanize %}
{% block title %}Lan Complain{% endblock %}



{% block apps %}
    <div class="profile-content">
  <div class="page-header">
    <a href="{% url 'ask' %}" class="btn btn-primary pull-right">
      <span class="glyphicon glyphicon-bullhorn"></span> {% trans "Register Your Complain" %}
    </a>
    <h1>{% trans "Complains" %}</h1>
  </div>
  <div class="questions">
    <ul class="nav nav-tabs" style="margin-bottom: 1.4em">
      <li{% if active == 'unanswered' %} class="active"{% endif %}><a href="{% url 'unanswered' %}">{% trans "Unanswered" %}</a></li>
      <li{% if active == 'answered' %} class="active"{% endif %}><a href="{% url 'answered' %}">{% trans "Answered" %}</a></li>
      <li{% if active == 'all' %} class="active"{% endif %}><a href="{% url 'all' %}">{% trans "All Complains" %}</a></li>
    </ul>
    {% for question in questions %}
      {% include 'lan_complain/partial_question.html' with question=question %}
    {% empty %}
      <h4 class="no-data">{% trans "No complain to display" %}</h4>
    {% endfor %}
    {% include 'paginator.html' with paginator=questions %}
  </div>
    </div>
{% endblock apps %}