events/urls.py
from django.conf.urls import url
from .views import display

urlpatterns = [
    url(r'^events/$', display),
]

por/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from search import views as search_views
from django.conf import settings
from django.conf.urls.static import static
from activities import views as activities_views
urlpatterns = [
    url(r'^$',views.site_redirect),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/',views.home),
    url(r'^accounts/profile_edit/(?P<pk>[\-\w]+)/$', views.edit_user, name='account_update'),
    url(r'^accounts/profile_view/(?P<pk>[\-\w]+)/$',views.get_user, name = 'account_view'),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^profile/(?P<username>[^/]+)/$', views.profile, name='profile'),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    url(r'', include('events.urls')),
    url(r'^messages/', include('messenger.urls')),
    url(r'^settings/picture/$', views.picture, name='picture'),
    url(r'^settings/upload_picture/$', views.upload_picture,
        name='upload_picture'),
    url(r'^settings/save_uploaded_picture/$', views.save_uploaded_picture,
        name='save_uploaded_picture'),
    url(r'^feeds/', include('feeds.urls')),
    url(r'^lan_complain/', include('lan_complain.urls')),
    url(r'^enotices/', include('enotices.urls')),
    url(r'^notifications/$', activities_views.notifications,
        name='notifications'),
    url(r'^notifications/last/$', activities_views.last_notifications,
        name='last_notifications'),
    url(r'^notifications/check/$', activities_views.check_notifications,
        name='check_notifications'),
    url(r'^LostAndFound/', include('lost_found.urls', namespace="laf")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

events/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=120)
    image = models.FileField(null=True, blank=True)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    author = models.ForeignKey(User, default= '')


    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-timestamp", "-updated"]

por/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import hashlib
import urllib
import os
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings


class UserProfile(models.Model):
    BRANCH_CHOICES=(
        ('0','Bio-Chemical Engg.'),
        ('1', 'Bio-Medical Engg'),
        ('2', 'Ceramic Engg.'),
        ('3', 'Chemical Engg.'),
        ('4', 'Chemistry'),
        ('5', 'Civil Engg.'),
        ('6', 'Computer Engg.'),
        ('7', 'Electrical Engg.'),
        ('8', 'Electronic Engg.'),
        ('9', 'Material Sc. and Tech.'),
        ('10', 'Mathematical Sciences'),
        ('11', 'Mechanical Engg.'),
        ('12', 'Metallurgical Engg.'),
        ('13', 'Mining Engg.'),
        ('14', 'Pharmaceutical Engineering & Technology'),
        ('15', 'Physics'),

    )
    YEAR_CHOICES=(
        ('0','1st'),
        ('1','2nd'),
        ('2','3rd'),
        ('3','4th'),
        ('4','5th'),

    )


    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default='', blank=True)
    phone = models.CharField(max_length=20, blank=True, default='')
    city = models.CharField(max_length=100, default='', blank=True)
    branch = models.CharField(max_length=100, default='', blank=True,choices=BRANCH_CHOICES)
    year = models.CharField(max_length=100, default='', blank=True,choices=YEAR_CHOICES)


    def get_picture(self):
        no_picture = '/static/img/1.jpg'
        try:
            filename = settings.MEDIA_ROOT + '/profile_pictures/' + \
                       self.user.username + '.jpg'
            picture_url = settings.MEDIA_URL + '/profile_pictures/' + \
                          self.user.username + '.jpg'
            if os.path.isfile(filename):
                return picture_url
            else:
                gravatar_url = 'http://www.gravatar.com/avatar/{0}?{1}'.format(
                    hashlib.md5(self.user.email.lower()).hexdigest(),
                    urllib.urlencode({'d': no_picture, 's': '256'})
                )
                return gravatar_url
        except Exception:
            return no_picture

    def get_screen_name(self):
        try:
            if self.user.get_full_name():
                return self.user.get_full_name()
            else:
                return self.user.username
        except:
            return self.user.username



def create_profile(sender, **kwargs):
    user = kwargs["instance"]

    if kwargs["created"]:
        user_profile = UserProfile(user=user)
        user_profile.save()


post_save.connect(create_profile, sender=User)

events/views.py
from django.shortcuts import render
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

def display(request):
    queryset_list = Post.objects.all()
    paginator = Paginator(queryset_list, 25)  # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        "object_list": queryset,
        "title": "Event List"
    }
    return render(request, "events.html", context)

templates/base.html
{% load staticfiles %}

	<!DOCTYPE html>
	<html>

	<head>

	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">

	    <title>IIT-BHU Web Portal</title>

	    <!-- Core CSS - Include with every page -->
        <link href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/flickity.css'%}" rel="stylesheet">
	    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'bootstrap-social-gh-pages/bootstrap-social.less/bootstrap-social.css' %}" rel="stylesheet">
         <link href="{% static 'css/jquery.Jcrop.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/messages.css' %}" rel="stylesheet">
        <link href="{% static 'css/articles.css' %}" rel="stylesheet">
        <link href="{% static 'css/feeds.css' %}" rel="stylesheet">
        <link href="{% static 'css/search.css' %}" rel="stylesheet">
        <link href="{% static 'css/notifications.css' %}" rel="stylesheet">
        <link href="{% static 'css/questions.css' %}" rel="stylesheet">



 <script src = "{% static 'js/jquery.min.js' %}"></script>
        <script src='{% static 'js/flickity.pkgd.min.js' %}'></script>

	    <script src = "{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/java.js' %}" rel="script"></script>
        <script src="{% static 'js/jquery.typeahead.bundle.js' %}"></script>
        <script src="{% static 'js/check_messages.js' %}"></script>
        <script src="{% static 'js/jquery.Jcrop.min.js' %}"></script>
        <script src="{% static 'js/picture.js' %}"></script>
        <script src="{% static 'js/search.js' %}"></script>
        <script src="{% static 'js/articles.js' %}"></script>
        <script src="{% static 'js/feeds.js' %}"></script>
        <script src="{% static 'js/notifications.js' %}"></script>
        <script src="{% static 'js/questions.js' %}"></script>
        <script src="{% static 'js/jquery.bullseye-1.0-min.js' %}"></script>
        <script src="{% static 'js/messages.typehead.js' %}"></script>
        <script type="text/javascript">
$(window).load(function() {
	$(".loader").fadeOut(1500);
})
</script>
    <script src="{% static 'js/messages.js' %}"></script>



	</head>

	<body>

<div class="container headerstyle">
    <div class="row">
        <div class="col-md-2"><img class="icon-iitbhu" style="width: 82px; height: 76px; padding-right: 0px; padding-left: 0px; margin-top: 7px; margin-left: 109px;" src="{% static 'img/icon/logo.png' %}"></div>
        <div class="col-md-10"><h2 class="head1">Student Activity Portal</h2>
                            <h4 class="head2">INDIAN INSTITUTE OF TECHNOLOGY(BANARAS HINDU UNIVERSITY) VARANASI</h4>
        </div>
    </div>
</div>
 <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header ">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand " href="/">HOME</a>
    </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li ><a href="#">Institute Web Commitee</a></li>
                <li><a href="#">Guidelines</a></li>
                {% if user.is_authenticated %}
                {% else %}
                <li><a href="{{ signup_url }}">REGISTER</a></li>
                {% endif %}

             </ul>
                {% if user.is_authenticated %}
                    <ul class="nav navbar-nav " >


                    <li class="search" style="left: 693px; top: 0px; height: 41px; padding-top: 4px; margin-top: 8px; border-left-width: 3px;">
                            <form role="search" action="{% url 'search' %}">
                            <input class="form-control input-sm" type="text" maxlength="64" placeholder="Search" name="q" style="top:5px">
                            <button class="btn btn-primary btn-sm tonsa" type="submit" >Search</button>
                             </form>
                    </li>

                    </ul>

                {% else %}
                {% endif %}

        </div>
  </div>
</nav>


	            {% block content %}
	            {% endblock %}

	    <!-- Core Scripts - Include with every page -->

          <!-- Carousel -->


	    {% block javascript %}
	    {% endblock %}

	</body>
<footer class="container-fluid text-center  ">

        <div class="copyrights footer" style="margin-top:10px;margin-bottom: 0; position:relative; padding-top:46px;">


            <a href="http://www.iitbhu.ac.in/alumni/" target="_blank">Alumni Portal </a>|  |<a href="#" target="_blank">Institute Portals </a>|  |<a href="https://www.placement.iitbhu.ac.in/" target="_blank">Placement</a>|  |<a href="https://www.iitbhu.ac.in" target="_blank">IIT-BHU official </a>
                <br>

            <p>Copyright © 2017-18 | Indian Institute Of Technology(Banaras Hindu University) Varanasi-221005 | Disclaimer</p>
        </div>
</footer>

	</html>

templates/events.html
{% extends 'home.html' %}


{% block apps %}

    <h1>{{ title }}</h1>

{% for obj in object_list %}
<div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">
      {%  if obj.image %}
        <img src="{{ obj.image.url }}" class="img-responsive">
      {% endif %}
      <div class="caption">
       <h3>{{ obj.title }}<small><br>{{ obj.timestamp|timesince }} ago</small></h3>

        <p>{{ obj.content|linebreaks|truncatechars:120 }}</p>
          <a href="{% url 'profile' obj.author.username %}" ><h6>{{ obj.author.first_name }} {{ obj.author.last_name }}</h6></a>
        <p><a href="#" class="btn btn-primary" role="button">View</a></p>
      </div>
    </div>
  </div>
<hr/>
</div>
{% endfor %}


<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>


{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
{% load static %}


<link rel='stylesheet prefetch' href='{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}'>
    <div class="container">
        <div class="col-md-3" >
            <div class="row profile">
                <div class="profile-sidebar" >
                    <!-- SIDEBAR USERPIC -->
				<div class="profile-userpic">
					<img src="{{ user.userprofile.get_picture }}" class="img-responsive" alt="">
				</div>
				<!-- END SIDEBAR USERPIC -->
				<!-- SIDEBAR USER TITLE -->
				<div class="profile-usertitle">
					<div class="profile-usertitle-name">
						<a href="{% url 'account_view' pk=user.id %}"> {{ user.first_name }} {{ user.last_name }}</a>
					</div>
					<div class="profile-usertitle-job">
						{{ user.userprofile.get_year_display }} year,{{ user.userprofile.get_branch_display }}
					</div>
                    <div class="profile-usertitle-job">
						{{ user.email }}
					</div>
                    <div>
                        message id : {{ user.username }}

                  <a href="#" id="notifications" data-container="body" data-toggle="popover" data-placement="bottom" title="Notifications">
                    <span class="fa fa-bell-o"></span>
                  </a>

                    </div>
				</div>
				<!-- END SIDEBAR USER TITLE -->
				<!-- SIDEBAR BUTTONS -->
				<div class="profile-userbuttons">
					<a href="{% url 'account_update' pk=user.id %}" type="button" class="btn btn-success btn-sm">Edit</a>
                    <a href="{% url 'picture'%}" type="button" class="btn btn-success btn-xs">Profile pic update</a>



				</div>
				<!-- END SIDEBAR BUTTONS -->
				<!-- SIDEBAR MENU -->
				<div class="profile-usermenu">
					<ul class="nav nav-tabs nav-stacked" >

                        <li >
							<a href="{% url 'inbox' %}"><i class="fa fa-inbox"></i><span class="badge pull-right" id="unread-count">0</span> Inbox</a>
						</li>
						<li >
							<a href="/events/">
							<i class="fa fa-dashboard"></i>
							Events </a>
						</li>
						<li>
							<a href="/lan_complain/">
							<i class="glyphicon glyphicon-user"></i>
							Lan Complain </a>
						</li>
						<li>
							<a href="/enotices/" >
							<i class="glyphicon glyphicon-ok"></i>
							e-Notices</a>
						</li>
                        <li>
							<a href="/LostAndFound/" >
							<i class="glyphicon glyphicon-ok"></i>
							Lost And Found</a>
						</li>
						<li>
							<a href="#">
							<i class="glyphicon glyphicon-flag"></i>
							About </a>
						</li>
					</ul>
				</div>
                  <aside class="sm-side">

                      <div class="inbox-body text-center">
                          <div class="btn-group">
                              <a class="btn mini btn-primary" href="/accounts/logout">
                                  <i class="fa fa-sign-out"></i>
                              </a>
                          </div>
                          <div class="btn-group">
                              <a class="btn mini btn-success" href="javascript:;">
                                  <i class="fa fa-phone"></i>
                              </a>
                          </div>
                          <div class="btn-group">
                              <a class="btn mini btn-info" href="javascript:;">
                                  <i class="fa fa-cog"></i>
                              </a>
                          </div>
                      </div>

                  </aside>
                </div>
         </div>
        </div>
         <div class="col-md-9" >
         <div class="loader"></div>
             {% block apps %}

                            <h2 class="well">Feeds</h2>
             {% endblock %}
         </div>
    </div>


{% endblock %}

templates/markdown_editor.html
{% load staticfiles %}
<script src="{% static 'js/jquery.selection.js' %}"></script>
<script src="{% static 'js/bootcamp.markdown.js' %}"></script>

<div class="markdown">
  <div class="modal fade" id="markdown_insert_link">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Insert Link</h4>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <label for="markdown_link_text" class="control-label">Link Text</label>
            <input type="text" class="form-control" id="markdown_link_text" placeholder="Link Text">
          </div>
          <div class="form-group">
            <label for="markdown_url" class="control-label">URL</label>
            <input type="text" class="form-control" id="markdown_url" placeholder="URL">
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary add_link" data-dismiss="modal">Ok</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="markdown_insert_picture">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Insert Image</h4>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <label for="markdown_picture_url" class="control-label">Picture URL</label>
            <input type="text" class="form-control" id="markdown_picture_url" placeholder="Picture URL">
          </div>
          <div class="form-group">
            <label for="markdown_alt_text" class="control-label">Alt Text</label>
            <input type="text" class="form-control" id="markdown_alt_text" placeholder="Alt Text">
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary add_picture" data-dismiss="modal">Ok</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="markdown_help">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Help</h4>
        </div>
        <div class="modal-body">
          <p>You can learn more about markdown syntax <a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">here</a>.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <div class="btn-group">
    <button type="button" class="btn btn-default btn-sm" ref="header"><span class="glyphicon glyphicon-header"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="bold"><span class="glyphicon glyphicon-bold"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="italic"><span class="glyphicon glyphicon-italic"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="list"><span class="glyphicon glyphicon-list"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="link"><span class="glyphicon glyphicon-link"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="picture"><span class="glyphicon glyphicon-picture"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="indent-left"><span class="glyphicon glyphicon-indent-left"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="indent-right"><span class="glyphicon glyphicon-indent-right"></span></button>
  </div>
  <button type="button" data-toggle="modal" data-target="#markdown_help" class="btn btn-link btn-sm pull-right"><span class="glyphicon glyphicon-question-sign"></span> Help</button>
</div>
<script>$(function(){$("#{{ textarea }}").markdown();});</script>

templates/paginator.html
<ul class="pagination">
  {% if paginator.has_previous %}
    <li><a href="?page={{ paginator.previous_page_number }}">&laquo;</a></li>
  {% else %}
    <li class="disabled"><span>&laquo;</span></li>
  {% endif %}
  {% for i in paginator.paginator.page_range %}
    {% if paginator.number == i %}
      <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
      <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
  {% endfor %}
  {% if paginator.has_next %}
    <li><a href="?page={{ paginator.next_page_number }}">&raquo;</a></li>
  {% else %}
    <li class="disabled"><span>&raquo;</span></li>
  {% endif %}
</ul>

templates/profile_edit.html
{% extends 'home.html' %}

{% block apps %}
<div class="profile-content">
        <h2 class="well">Edit Your Profile</h2>
          <form action="." method="POST" class="padding">
            {% csrf_token %} {{ noodle_form.as_p }}
            <div class="divider"></div>
            {{ formset.management_form }}
                {{ formset.as_p }}
            <button type="submit" class="btn-floating btn-large waves-light waves-effect"><i class="large material-icons">done</i></button>
            <a href="#" onclick="window.history.back(); return false;" title="Cancel" class="btn-floating waves-effect waves-light red"><i class="material-icons">history</i></a>

        </form>
</div>

{% endblock %}

templates/profile_view.html
{% extends 'home.html' %}
{% load static %}
{% block apps %}






          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">PROFILE</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="{{ user.userprofile.get_picture }}" class="img-responsive"> </div>

                <div class="col-xs-10 col-sm-10 hidden-md hidden-lg"> <br>
                  <dl>
                    <dt>DEPARTMENT:</dt>
                    <dd>Administrator</dd>
                    <dt>HIRE DATE</dt>
                    <dd>11/12/2013</dd>
                    <dt>DATE OF BIRTH</dt>
                       <dd>11/12/2013</dd>
                    <dt>GENDER</dt>
                    <dd>Male</dd>
                  </dl>
                </div>
                <div class=" col-md-9 col-lg-9 ">
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>Name:</td>
                        <td>{{ user.first_name }} {{ user.last_name }}</td>
                      </tr>
                      <tr>
                        <td>Year:</td>
                        <td>{{ user.userprofile.get_year_display }}</td>
                      </tr>
                      <tr>
                        <td>Department:</td>
                        <td>{{ user.userprofile.get_branch_display }}</td>
                      </tr>

                      <tr>
                        <td>Date of Birth:</td>
                        <td>01/24/1988</td>
                      </tr>

                         <tr>
                             <tr>
                        <td>Gender:</td>
                        <td>Male</td>
                      </tr>
                        <tr>
                        <td>Bio:</td>
                        <td>{{ user.userprofile.bio }}</td>
                      </tr>
                      <tr>
                        <td>Email</td>
                        <td>{{ user.email }}</td>
                      </tr>
                      <tr>
                        <td>Phone Number</td>
                        <td>{{ user.userprofile.phone }}
                        </td>

                      </tr>

                    </tbody>
                  </table>


                </div>
              </div>
            </div>


          </div>



{% endblock %}